default[:jmxtrans][:version]   = '1.0.0'
default[:jmxtrans][:etc]       = '/var/lib/jmxtrans'
default[:jmxtrans][:lib]       = '/usr/share/jmxtrans'
default[:jmxtrans][:log]       = '/var/log/jmxtrans'
default[:jmxtrans][:log_level] = 'DEBUG'
default[:jmxtrans][:url]       = 'DEFAULT_URL'
